# **Numpy**

In [1]:
import numpy as np
import random
import scipy.stats as sps
import cv2

### **Задание 1**
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами - без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.58015655 0.19169573 0.83229945 ... 0.03024394 0.34285245 0.9827727 ]
 [0.19648098 0.04879319 0.19803945 ... 0.17745441 0.29365467 0.73577412]
 [0.20155159 0.75839301 0.06221622 ... 0.40701187 0.94534876 0.56941156]
 ...
 [0.84400453 0.09415362 0.90166302 ... 0.06457979 0.45880575 0.24023844]
 [0.65527497 0.16414479 0.27521173 ... 0.31414126 0.33281071 0.94393731]
 [0.29583932 0.42301091 0.11955432 ... 0.8127968  0.04824725 0.39997135]]
[[0.32018282 0.09040502 0.43721488 ... 0.53763607 0.92446622 0.53552865]
 [0.02313402 0.05436508 0.48961376 ... 0.22857983 0.41759154 0.24807399]
 [0.91423492 0.97304421 0.84614392 ... 0.25219032 0.50282422 0.3658917 ]
 ...
 [0.42658777 0.51911507 0.10508198 ... 0.49134722 0.68121936 0.3739822 ]
 [0.87780222 0.9378725  0.58514866 ... 0.3113496  0.8411716  0.97617702]
 [0.60653861 0.54630997 0.86904972 ... 0.39880104 0.89685904 0.28532264]]


Без использования **numpy**

In [16]:
def matrix_multiply(matrix_a: list[list[(int, float)]], matrix_b: list[list[(int, float)]]) -> list[list[(int, float)]]:
    """
    Умножение двух квадратных матриц без использования библиотеки NumPy.

    Аргументы:
    - matrix_a: Первая матрица.
    - matrix_b: Вторая матрица.
    """
    size = len(matrix_a)
    result = [[0 for _ in range(size)] for _ in range(size)]

    for i in range(size):
        for j in range(size):
            for k in range(size):
                result[i][j] += matrix_a[i][k] * matrix_b[k][j]

    return result


result_without_numpy = matrix_multiply(matrix_a=[[1, 2, 3], [4, 5, 6], [7, 8, 9]], matrix_b=[[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(result_without_numpy)

[[30, 24, 18], [84, 69, 54], [138, 114, 90]]


C использованием **numpy**

In [19]:
def matrix_multiply_np(matrix_a: list[list[(int, float)]], matrix_b: list[list[(int, float)]]) -> list[list[(int, float)]]:
    """
    Умножение двух квадратных матриц с использованием библиотеки NumPy.

    Аргументы:
    - matrix_a: Первая матрица.
    - matrix_b: Вторая матрица.
    """
    result = np.dot(matrix_a, matrix_b)

    return result


result_with_numpy = matrix_multiply_np(matrix_a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), matrix_b=np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]]))
print(result_with_numpy)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [20]:
%%time
# засечем время работы функции без NumPy
M1 = matrix_multiply(matrix_a=[[1, 2, 3], [4, 5, 6], [7, 8, 9]], matrix_b=[[9, 8, 7], [6, 5, 4], [3, 2, 1]])

CPU times: user 27 µs, sys: 3 µs, total: 30 µs
Wall time: 35.3 µs


In [21]:
%%time
# засечем время работы функции с NumPy
M2 = matrix_multiply_np(matrix_a=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), matrix_b=np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]]))

CPU times: user 338 µs, sys: 793 µs, total: 1.13 ms
Wall time: 1.15 ms


In [22]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

0

### **Задание 2**

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [29]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.31642943 0.8806064  0.61240425] [0.18472059 0.78937272 0.69450196]


In [30]:
def scalar_product(a,b):
    s = 0
    for x, y in zip(a, b):
        s += x * y
    return s

In [31]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [32]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 24 µs, sys: 3 µs, total: 27 µs
Wall time: 31.5 µs
CPU times: user 159 µs, sys: 22 µs, total: 181 µs
Wall time: 356 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Методы NumPy более **эффективны** по нескольким причинам. Во-первых, NumPy реализован на языке C, что позволяет выполнять вычисления быстрее по сравнению с чистым Python. Кроме того, NumPy использует непрерывное хранилище памяти и оптимизированные алгоритмы, сводя к минимуму накладные расходы и повышая производительность. NumPy также поддерживает векторизованные операции, которые могут обрабатывать несколько элементов одновременно, что снижает необходимость в явных циклах.

**Что касается скорости**, NumPy известен своими возможностями быстрых вычислений. Он предлагает эффективные числовые операции, такие как манипуляции с массивами, математические функции и процедуры линейной алгебры. Используя оптимизированные библиотеки C и Fortran, NumPy может выполнять вычисления значительно быстрее, чем традиционный код Python, что делает его популярным выбором для научных и числовых вычислительных задач.

------------------

### **Задание 3**
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [26]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    diag_elements = np.diagonal(a)
    even_diag_elements = diag_elements[diag_elements % 2 == 0]
    res = even_diag_elements.sum() if even_diag_elements.size > 0 else 0

    return res

In [27]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[7, 3, 4, 5, 9],
       [6, 2, 8, 8, 2],
       [3, 2, 4, 5, 1],
       [2, 6, 5, 9, 3],
       [6, 9, 3, 8, 1]])

In [28]:
%%time
# засечем время работы функции с NumPy
result = np_diag_2k(a)
print("Сумма четных диагональных элементов:", result)

Сумма четных диагональных элементов: 6
CPU times: user 1.62 ms, sys: 0 ns, total: 1.62 ms
Wall time: 1.64 ms


### **Задание 4**
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [36]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    x = A.shape[1]
    cumsum = np.cumsum(A, axis=1)
    val = np.arange(1, x + 1).reshape(1, x)
    return cumsum / val

In [38]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = np.random.uniform(0, 1, size = (10**3, 5))
A

array([[0.82841886, 0.91602844, 0.34352664, 0.95806383, 0.97230779],
       [0.06714408, 0.25699066, 0.90066144, 0.14388723, 0.24096063],
       [0.53676847, 0.47144426, 0.21515086, 0.73032996, 0.023708  ],
       ...,
       [0.2396483 , 0.80552444, 0.71444938, 0.32520058, 0.21033781],
       [0.85203261, 0.74344961, 0.7920398 , 0.26612456, 0.88640118],
       [0.00314792, 0.08025192, 0.84256902, 0.54582415, 0.03859836]])

In [39]:
%time S2 = np_sec_av(A)
S2# функция, решающая задачу с помощью NumPy

CPU times: user 1.14 ms, sys: 19 µs, total: 1.16 ms
Wall time: 1.17 ms


array([[0.82841886, 0.87222365, 0.69599131, 0.76150944, 0.80366911],
       [0.06714408, 0.16206737, 0.40826539, 0.34217085, 0.32192881],
       [0.53676847, 0.50410636, 0.40778786, 0.48842339, 0.39548031],
       ...,
       [0.2396483 , 0.52258637, 0.58654071, 0.52120568, 0.4590321 ],
       [0.85203261, 0.79774111, 0.79584067, 0.66341165, 0.70800955],
       [0.00314792, 0.04169992, 0.30865629, 0.36794825, 0.30207828]])

### **Задание 5**
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

**Пример:** encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [49]:
def np_encode(a):
    elements = []
    counts = []

    for key, group in groupby(a):
        elements.append(key)
        counts.append(len(list(group)))

    elements_array = np.array(elements)
    counts_array = np.array(counts)

    return elements_array, counts_array

In [50]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
x, num = np_encode(X)
print(x, num)

CPU times: user 45 µs, sys: 6 µs, total: 51 µs
Wall time: 54.6 µs
[1 2 3 1 5 2 3] [1 2 2 2 2 1 2]


### **Задание 6**

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

**Пример:**  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [55]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    transformed_X = X.copy()
    transformed_X[1::2] = a
    transformed_X[::2] **= 3
    reversed_transformed_X = transformed_X[::-1]
    result = np.concatenate((X, reversed_transformed_X[::-1]))

    return result

In [56]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 3)
S2

CPU times: user 80 µs, sys: 0 ns, total: 80 µs
Wall time: 84.4 µs


array([  1,   3,   5,   7,   9,   1,   3, 125,   3, 729])