# **Numpy**

In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2

### **Задание 1**
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами - без использования пакета ***numpy*** и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.58015655 0.19169573 0.83229945 ... 0.03024394 0.34285245 0.9827727 ]
 [0.19648098 0.04879319 0.19803945 ... 0.17745441 0.29365467 0.73577412]
 [0.20155159 0.75839301 0.06221622 ... 0.40701187 0.94534876 0.56941156]
 ...
 [0.84400453 0.09415362 0.90166302 ... 0.06457979 0.45880575 0.24023844]
 [0.65527497 0.16414479 0.27521173 ... 0.31414126 0.33281071 0.94393731]
 [0.29583932 0.42301091 0.11955432 ... 0.8127968  0.04824725 0.39997135]]
[[0.32018282 0.09040502 0.43721488 ... 0.53763607 0.92446622 0.53552865]
 [0.02313402 0.05436508 0.48961376 ... 0.22857983 0.41759154 0.24807399]
 [0.91423492 0.97304421 0.84614392 ... 0.25219032 0.50282422 0.3658917 ]
 ...
 [0.42658777 0.51911507 0.10508198 ... 0.49134722 0.68121936 0.3739822 ]
 [0.87780222 0.9378725  0.58514866 ... 0.3113496  0.8411716  0.97617702]
 [0.60653861 0.54630997 0.86904972 ... 0.39880104 0.89685904 0.28532264]]


Без использования **numpy**

In [ ]:
def mult(a, b):
  # Инициализируем результирующую матрицу нулями
    result = [[0 for x in range(len(b[0]))] for y in range(len(a))]

    # Выполняем умножение матриц
    for i in range(len(a)):
        for j in range(len(b[0])):
            for k in range(len(b)):
                result[i][j] += a[i][k] * b[k][j]

    return result

# Пример использования
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = [[9, 8, 7], [6, 5, 4], [3, 2, 1]]
result = mult(a, b)
print(result)

[[30, 24, 18], [84, 69, 54], [138, 114, 90]]


C использованием **numpy**

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

def np_mult(a, b):
    result = np.dot(a, b)
    return result
print(result)

[[30, 24, 18], [84, 69, 54], [138, 114, 90]]


In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 74 µs, sys: 0 ns, total: 74 µs
Wall time: 79.2 µs


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 49 µs, sys: 6 µs, total: 55 µs
Wall time: 60.3 µs


In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

0

### **Задание 2**

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [144]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.82140637 0.09170166 0.3345053 ] [0.60190498 0.49297985 0.29416488]


In [145]:
def scalar_product(a,b):
    s = 0
    for x, y in zip(a, b):
        s += x * y
    return s

In [146]:
def np_scalar_product(a,b):
    s = np.dot(a, b)
    return s

In [147]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 25 µs, sys: 4 µs, total: 29 µs
Wall time: 31.2 µs
CPU times: user 110 µs, sys: 15 µs, total: 125 µs
Wall time: 129 µs


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

**Ответ:** Методы NumPy более **эффективны** по нескольким причинам. Во-первых, NumPy реализован на языке C, что позволяет выполнять вычисления быстрее по сравнению с чистым Python. Кроме того, NumPy использует непрерывное хранилище памяти и оптимизированные алгоритмы, сводя к минимуму накладные расходы и повышая производительность. NumPy также поддерживает векторизованные операции, которые могут обрабатывать несколько элементов одновременно, что снижает необходимость в явных циклах.

**Что касается скорости**, NumPy известен своими возможностями быстрых вычислений. Он предлагает эффективные числовые операции, такие как манипуляции с массивами, математические функции и процедуры линейной алгебры. Используя оптимизированные библиотеки C и Fortran, NumPy может выполнять вычисления значительно быстрее, чем традиционный код Python, что делает его популярным выбором для научных и числовых вычислительных задач.

------------------

### **Задание 3**
Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [161]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
  diag_one = np.diag(a).tolist()
  matrix = np.fliplr(a)
  diag_two = np.diag(matrix).tolist()
  *res, = filter(lambda x: int(x) % 2 == 0, (diag_one + diag_two))
  return sum(res)

In [158]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[8, 8, 9, 3, 7],
       [6, 4, 8, 3, 4],
       [8, 2, 6, 9, 2],
       [6, 5, 3, 9, 5],
       [3, 4, 1, 4, 1]])

In [156]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 104 µs, sys: 0 ns, total: 104 µs
Wall time: 110 µs


26

### **Задание 4**
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, \ldots, x_n)$ массива $X$  строит строчку $s = (s_1, s_2, \ldots, s_n)$, где $s_k=\frac{x_1+...+x_k}{k}$, а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и $X$.

In [198]:
# функция, решающая задачу с помощью NumPy
def np_sec_av(A):
    x = A.shape[1]
    cumsum = np.cumsum(A, axis=1)
    val = np.arange(1, x + 1).reshape(1, x)
    return cumsum / val

In [204]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = np.random.uniform(0, 1, size = (10**3, 5))
A

array([[0.38832423, 0.14570828, 0.84066722, 0.94187959, 0.957545  ],
       [0.29712881, 0.99880901, 0.39778514, 0.9941051 , 0.27448456],
       [0.82002785, 0.20593213, 0.7063466 , 0.79148818, 0.88287113],
       ...,
       [0.41090894, 0.91662962, 0.79875842, 0.91040884, 0.36883711],
       [0.10150537, 0.03921204, 0.04427059, 0.93464651, 0.8446774 ],
       [0.7693284 , 0.5235816 , 0.63578829, 0.52365484, 0.75357812]])

In [205]:
%time S2 = np_sec_av(A)
S2

CPU times: user 569 µs, sys: 0 ns, total: 569 µs
Wall time: 580 µs


array([[0.38832423, 0.26701626, 0.45823325, 0.57914483, 0.65482487],
       [0.29712881, 0.64796891, 0.56457432, 0.67195702, 0.59246252],
       [0.82002785, 0.51297999, 0.57743552, 0.63094869, 0.68133318],
       ...,
       [0.41090894, 0.66376928, 0.70876566, 0.75917645, 0.68110858],
       [0.10150537, 0.0703587 , 0.06166267, 0.27990863, 0.39286238],
       [0.7693284 , 0.646455  , 0.64289943, 0.61308829, 0.64118625]])

### **Задание 5**
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

**Пример:** encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [180]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    unique_values, value_counts = np.unique(a, return_counts=True)
    return unique_values, value_counts

In [181]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)
x, num

CPU times: user 197 µs, sys: 0 ns, total: 197 µs
Wall time: 203 µs


(array([1, 2, 3, 5]), array([3, 3, 4, 2]))

### **Задание 6**

Пусть задан некоторый одномерный массив $X$. Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число $a$ (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив $X$ при этом должен остаться *без изменений*. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.  

**Пример:**  
X = [100, 200, 300, 400, 500] -> [100, a, 300, a, 500] -> [500^3, a, 300^3, a, 100^3] -> склеиваем -> [100, 200, 300, 400, 500, 500^3, a, 300^3, a, 100^3]

In [182]:
# функция, решающая задачу с помощью NumPy
from copy import copy

def np_transformation(X, a=1):
    """
    param X: array
    """
    modified_X = X.copy()
    modified_X[1::2] = a  # Замена элементов с нечетными индексами на a
    modified_X[::2] **= 3  # Возведение элементов с четными индексами в куб
    reversed_modified_X = modified_X[::-1]  # Обратный порядок элементов

    merged_array = np.concatenate((X, reversed_modified_X))  # Слияние массивов
    result = merged_array[::-1]  # Вывод в обратном порядке

    return result

In [186]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 3)
S2

CPU times: user 100 µs, sys: 13 µs, total: 113 µs
Wall time: 119 µs


array([  1,   3, 125,   3, 729,   9,   7,   5,   3,   1])